make shellcheck conform, port to use my new template for handling args

diff --git a/envm b/envm
--- a/envm
+++ b/envm
@@ -3,30 +3,29 @@
 # Desc: Handles initialization of all scripts
 set -u
 
-for script in $envm/scripts/*; do
+for script in "$ENVM"/scripts/*; do
 	source "$script"
 done
 
-if [ -z "${envm_wdir+x}" ]; then
-  echo "could not find envm_wdir environment variable"
-	echo "Please set envm_wdir variable like this echo 'export envm_wdir='~/some/dir'' >> ~/.bashrc "
+if [[ -z "$ENVM_WDIR" ]]; then
+  echo "could not evalulate ENVM_WDIR environment variable."
 fi
 
-if [ ! -z "${envm_wdir+x}" ]; then
-	if [ ! -d "$envm_wdir" ]; then
-  	echo "could not find working directory as requested in envm_wdir"
+if [[ -z "$ENVM_WDIR" ]]; then
+	if [[ ! -d "$ENVM_WDIR" ]]; then
+  	echo "could not find working directory as requested in ENVM_WDIR"
 	fi
 fi
 
-# Message ------------------------------------------------
-figlet "Hello, $USER"
-neofetch
-fortune
-# ------------------------------------------------
+# Message on SHELL start
+figlet "Hello, $USER" || echo "Hello, $USER"
+neofetch || true
+fortune || true
+##########
 
 # automatic update looking for the value in ./cache/start_epoch.dat
-if [[ $envm_auto_update_days -le 1 ]]; then
-	if [ ! -z "${envm+x}" ]; then
+if [[ $ENVM_AUTO_UPDATE_DAYS -le 1 ]]; then
+	if [ -z "${ENVM+x}" ]; then
 		dat_file="$HOME/.cache/envm/start_epoch.dat"
 
 		if [ ! -d "$HOME/.cache/envm" ]; then
@@ -34,11 +33,11 @@ if [[ $envm_auto_update_days -le 1 ]]; then
 		fi
 
   	if [ ! -f "$dat_file" ]; then
-   		date +%s > $dat_file
+   		date +%s > "$dat_file"
   	fi
 
-  	declare -i update_epoch=$(( 60 * 60 * 24 * $envm_auto_update_days + $(cat $dat_file) ))
-  	if [[ "$(date +%s)" -ge $update_epoch ]]; then
+  	declare -i update_epoch=$(( 60 * 60 * 24 * "$ENVM_AUTO_UPDATE_DAYS" + $(cat "$dat_file") ))
+  	if [[ "$(date +%s)" -ge "$update_epoch" ]]; then
     	date +%s > "$dat_file"
 			envmupdate
   	fi
diff --git a/scripts/today b/scripts/today
--- a/scripts/today
+++ b/scripts/today
@@ -1,69 +1,85 @@
 #!/bin/bash
 # Author: lukasjoc
-# Desc: TODAY is the really simple todo command using $EDITOR for writing and a git repo for hosting all things
+# License: MIT
+# Desc: today the really simple todo command using $EDITOR for writing and a git repo for hosting all things
+#######
 set -u
 
-#	write and update todos, sync between systems. Uses a git repos for storage
 today() {
+	local todo_name todo_repository todo_collection current_todo
 
-	local todo_name="$(date +'%d.%m.%y').md"
-	local todo_repository="$HOME/.local/share/todo" # Following XDG path conventions
-	local todo_collection="$(date +'%m')_$(date +'%y')"
-	local current_todo="$todo_repository/$todo_collection/$todo_name"
+	todo_name="$(date +'%d.%m.%y').md"
+	todo_repository="$HOME/.local/share/todo" # Following XDG path conventions
+	todo_collection="$(date +'%m')_$(date +'%y')"
+	current_todo="$todo_repository/$todo_collection/$todo_name"
 
-	# Create Month dir if not present
+	# Create month dir if not present
 	if [[ -d "$todo_repository/$todo_collection" ]]; then
 		mkdir -p "$todo_repository/$todo_collection"
-	fi 
-
-	if [ "$#" -le 0 ]; then
- 		# fallback is cat should be on all system hence less is not on mac per defaul`t
-		less "$current_todo" || cat "$current_todo"
-		return
 	fi
+
+	__usage() {
+		printf '\n%s\n\n' "Manage todos without overhead and within the workflow"
+		printf '%s\n\n' "USAGE:"
+		printf '%s\n\n'  " today [ -h ] [ new (With: $EDITOR) ]
+		[ update (With: $EDITOR) ]
+		[ save ] [ sync ] [ list ]"
+	}
 	
-	if [[ "$1" == "--save" || "$1" == "-s" ]]; then
+	__change() {
+		"$EDITOR" "$current_todo"
+		return 0
+	}
+
+	__save() {
 		cd "$todo_repository" || exit
- 		git add "$current_todo" && git commit -m "add current todo $todo_name"
+		git add "$current_todo" && git commit -m "add current todo $todo_name"
 		git push
 		cd - || exit
-		return	
-	fi
+		return 0
+	}
 
-	if [[ "$1" == "--sync" || "$1" == "-sy" ]]; then
+	__sync() {
 		cd "$todo_repository" || exit
-		git checkout master
-		git pull --rebase --stat origin master
-		cd - || exit
-		return
+		git checkout main
+		git pull --rebase --stat origin main
+		cd "$OLDPWD" || exit
+
+		return 0
+	}
+
+	__list() {
+		ls -R "$todo_repository"
+		return 0
+	}
+
+	# list current todolist for the current day
+	# using less or cat
+	if [[ "$#" == "0" ]]; then
+		less "$current_todo" || cat "$current_todo"
+		return 0
 	fi
 
-	if [[ "$1" == "--list" || "$1" == "--ls"  ]]; then
-		ls -R ${todo_repository:?}/* || return
-	fi
+	## handle single flags upper and lowercase
+	local opt
+	local OPTARG
+	local OPTIND
+	while getopts ":h" opt; do
+		case ${opt} in
+			h) __usage;;
+			\?) echo "Invalid Option: -$OPTARG" 1>&2;  return 1;;
+		esac
+	done
 	
-	if [[ "$1" == "--update" || "$1" == "-u" || "$1" == "--new" || "$1" == "-n" ]]; then
-		"$EDITOR" "$current_todo"
-		return
-	fi
-	
-	# print help
-	if [[ "$1" == "--help" || "$1" == "-h" || "$#" -gt 1 ]]; then
+	local cmd
+	cmd="${1:-}"; shift
+	case "$cmd" in
+		new) __change;;
+		update) __change;;
+		save) __save;;
+		sync) __sync;;
+		list) __list;;
+	esac
 
- 	 	printf '\n%s\n\n' "Manage todos without overhead and within the workflow"
-
-  	printf '%s\n\n' "USAGE:"
-  	printf '%s\n\n'  " today <FlAG>"
-
-  	printf '%s\n\n' "FlAGS:"
-  	printf '%s\n' " -h --help help for this bash script"
-  	printf '%s\n' " -sy --sync sync current todo repository"
-  	printf '%s\n' " -s,--save save current todo repository"
-		printf '%s\n' " -u,--update update current todo (default: $EDITOR)"
-  	printf '%s\n' " -n,--new create new todo for the current day (default: $EDITOR)"
-  	printf '%s\n\n' " -ls,--list list todos recursively"
-
-  	return
-	fi
-
+	shift $((OPTIND -1))
 }
diff --git a/scripts/xdgm b/scripts/xdgm
--- a/scripts/xdgm
+++ b/scripts/xdgm
@@ -2,69 +2,72 @@
 # Author: lukasjoc
 # License: MIT
 # Desc: Manage your XDG_* path. Show contents & delete stuff from it
+#######
+set -u
 
 xdgm() {
 
-	local status_color="\e[1;32m"
+	__usage() {
+		printf '\n%s\n\n' "Manage your XDG PATH. Show contents & delete stuff from it"
+		printf '%s\n\n'  " xdgm [ -h ] [ rm -n <name> ]"
+	}
 
+	local status_color="\e[1;32m"
 	local -a XDG_PATHS=(
-		"$HOME"/.config
-		"$HOME"/.local/share
-		"$HOME"/.cache
+		"$HOME/.config"
+		"$HOME/.local/share"
+		"$HOME/.cache"
 	)
 
-	# list if no args
-	if [[ "$#" == 0 ]]; then
+	__rm() {
+	
+		if [[ "$#" == 0 ]]; then
+			__usage
+			return 1
+		fi
 
 		for p in "${XDG_PATHS[@]}"; do
-			local total_apps="$(ls "$p" | wc -l | sed 's/ //g' )"
-			local total_size="$(du -sh "$p" | awk '{print $1}')"
-			echo -e "==> $status_color$p  AppsCount: $total_apps \ DiskSpace: $total_size  \e[0m"
+			local candidate="${p:?}/$*"
 
-			ls -F "$p" && echo
-		done
-
-		return 0
-	fi
-
-
-	if [[ "$1" == "rm" ]]; then
-
-		if [[ "$#" -le 1 ]]; then
-  		printf '%s\n\n'  "What do you want to delete?"
-  		printf '%s\n\n' "USAGE:"
-   		printf '%s\n\n'  " xdgm rm 'some_name' "
- 			return 1
- 		fi
-		
-		for p in "${XDG_PATHS[@]}"; do
- 			local candidate="${p:?}/$2"
-			if [[	-d "$candidate" ]]; then
- 				echo "Found candidate for $2 in $p Pruning..."
- 				rm -rf "$candidate"
+			if [[ -d "$candidate" ]]; then
+				echo "Found candidate for $* in $p Pruning..."
+				rm -rf "$candidate"
+				echo "removing $candidate"
 			else
- 				echo -e "Found $GREEN_FG 0 \e[0m candidates for $2 in $p Skipping..."
+				echo -e "Found $status_color 0 \e[0m candidates for $* in $p Skipping..."
 			fi
- 		done
 
- 	fi
+		done
+	}
 
-
-	if [[ "$1" == "--help" || $# -gt 2 ]]; then
-
- 		printf '%s\n\n' "Manage your XDG_* path. Show contents & delete stuff from it"
-
-  	printf '%s\n\n' "USAGE:"
-  	printf '%s\n\n'  " xdgm"
-  	printf '%s\n\n'  " xdgm [rm, --help]"
-
-  	printf '%s\n\n' "COMMANDS:"
-  	printf '%s\n\n' " rm remove folder from XDG DIRs (hint: recursive action)"
-
-		printf '%s\n\n' "FlAGS:"
-		printf '%s\n\n' " --help help for this bash script"
-
-  	return
+	# list XDG PATH
+	if [[ "$#" == "0" ]]; then
+		local total_apps total_size
+		for p in "${XDG_PATHS[@]}"; do
+			total_apps="$(find "$p" | wc -l | sed 's/ //g' )"
+			total_size="$(du -sh "$p" | awk '{print $1}')"
+			echo -e "==> $status_color$p  [ AppsCount: $total_apps \ DiskSpace: $total_size ]   \e[0m"
+			ls -F "$p" && return 1
+		done
 	fi
 
+
+	local opt OPTARG OPTIND
+	
+	# handle global flags
+	while getopts ":h" opt; do
+		case ${opt} in
+			h) __usage;;
+			\?) echo "Invalid Option: -$OPTARG" 1>&2;  return 1;;
+		esac
+	done
+
+	# handle global subcommands
+	local cmd
+	cmd="${1:-}"; shift
+	case "$cmd" in
+		rm) __rm "$@";;
+	esac
+
+	shift $((OPTIND -1))
 }
